# -*- coding: utf-8 -*-
"""CS3TERM4 project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gIEptRsZnJUjKlxXQzOWzXC94-CqoLl4
"""

! pip install pandas pillow numpy scikit-learn

import os
import zipfile
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from PIL import Image
from sklearn import metrics

zip_path = 'MRI'


def load_data(base_path, image_size=(128, 128)):
    images = []
    labels = []
    #os.chdir(base_path)
    class_names = os.listdir(base_path)


    for class_name in class_names:
        class_dir = os.path.join(base_path, class_name)
        if os.path.isdir(class_dir):
            for filename in os.listdir(class_dir):
                if filename.endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tiff')):
                    image_path = os.path.join(class_dir, filename)
                    image = Image.open(image_path).convert('L')
                    image = image.resize(image_size)
                    images.append(np.array(image))
                    labels.append(class_name)


    X = np.array(images)

    y = np.array(labels)



    X = X / 255.0


    X = X.reshape(-1, image_size[0], image_size[1], 1)

    return X, y

base_path = zip_path
X, y = load_data(base_path)

le = LabelEncoder()
y = le.fit_transform(y)


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

#from google.colab import drive
#drive.mount('/content/drive')

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

def create_model(input_shape):
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

input_shape = (128, 128, 1)
model = create_model(input_shape)
model.summary()

train_datagen = ImageDataGenerator(rotation_range=20, width_shift_range=0.2, height_shift_range=0.2, zoom_range=0.2, horizontal_flip=True)
train_generator = train_datagen.flow(X_train, y_train, batch_size=32)


history = model.fit(train_generator, epochs=10, validation_data=(X_test, y_test))


model.save('mri_alzheimers_model.h5')

test_loss, test_acc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc}")

y_pred = (model.predict(X_test) > 0.5).astype("int32")

confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print(confusion_matrix)

classification_report = metrics.classification_report(y_test, y_pred)
print(classification_report)

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0, 1])
plt.legend(loc='lower right')

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label = 'val_loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend(loc='upper right')

plt.show()